### ISSUE TITLE
Garbled Text in Autodesk Fusion Package Description

### ISSUE THREAD

**Issue by wjk** [svelez/chocolatey#2]
The title really says it all. Here is a screenshot illustrating the problem:

![Garbled Text Screenshot](https://cloud.githubusercontent.com/assets/1915951/22397757/abadf786-e546-11e6-8ed6-b00398bf6061.png)

I think this may be a character-encoding issue, but I cannot be certain. Thanks for looking into this!

**Comment by svelez** [comment]
Thanks for pointing this out.
It looks like the au module I've been using to monitor for updates changed something about how the nuspec is processed, and some non-printable characters were getting garbled, and it semms to compound with each auto update ☹️ 

I've gotten rid of as many of those as I could but the current version is still messing with the ®️ symbol.  So I've set the version back for now.

If I get a chance I might investigate what  is happening in au to see if t here is anything I can do to avoid this in current versions.

Leaving open until the next update to fusion 360 as i don't want to get the package version out of sync with the product.
